modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="vdaddon"
version="1.0.0"
displayName="Vampire Diaries Addon"
description='''Addon für Vampirism mit Daylight Ring, Originals und White Oak Stake'''
